task: korean_spacing_20210101
log_path: logs
bert_model: monologg/kobert
train_data_path: C:/Users/mcr/Desktop/sample/train.txt
val_data_path: C:/Users/mcr/Desktop/sample/val.txt
test_data_path: C:/Users/mcr/Desktop/sample/test.txt
max_len: 128
train_batch_size: 128
eval_batch_size: 128
dropout_rate: 0.1
distributed_backend: ddp
strategy: dp
gpus: 1